In [ ]:
import cv2
import os
import matplotlib.pyplot as plt
import numpy as np
import itertools
from collections import defaultdict
from mqtt_python.modules.ball_detection import pose_est_ball_from_img, Ball_Color

In [11]:
IMG_PATH = '../mask_blue.png'
IMG = cv2.imread(IMG_PATH)

In [ ]:
def pose_estimation_ball2(detection, mtx, dist):
    x, y, r = detection
    
    undistorted_points = cv2.undistortPoints(
    np.array([[[x, y]]], dtype=np.float32),
    mtx,
    dist
    )
    
    fx = mtx[0, 0]
    fy = mtx[1, 1]
    f = (fx + fy) / 2

    Z = f * (BALL_DIAMETER/2) / r
    
    x_n = undistorted_points[0][0][0]
    y_n = undistorted_points[0][0][1]

    X = x_n * Z
    Y = y_n * Z
    
    translation_vector = np.array([[X], [Y], [Z]])
    return translation_vector

    

def pose_est_ball_from_img2(image, Ball_Color = Ball_Color.BLUE):
    """
    Estimate the pose of a ball given its image.
    """
    
    #Cut off the top 20% of the image
    # image = image[int(image.shape[0]*0.3):, :]
    
    # Detect balls in the image
    detections = detect_balls(image, show=True, color = Ball_Color)
    if detections is None:
        return []
    
    # Estimate the pose of each detected ball
    poses = [pose_estimation_ball(detection, MTX, DIST) for detection in detections if detection is not None]
    
    # Sort by distance to camera
    # poses = sorted(poses, key = lambda x: np.linalg.norm(x))
    
    return poses

In [12]:

A = pose_est_ball_from_img(IMG, Ball_Color=Ball_Color.BLUE)

In [13]:
A

[array([[-0.2170805 ],
        [-0.14112782],
        [ 0.40208147]]),
 array([[-0.03712029],
        [-0.33612246],
        [ 0.9046833 ]]),
 array([[ 0.28464809],
        [-0.45775873],
        [ 1.03392378]]),
 array([[ 0.46381481],
        [-0.45761178],
        [ 1.03392378]])]

In [7]:
B = np.array([np.array([-0.22246914, -0.14470428,  0.40205969]),
 np.array([-0.03789932, -0.3424578 ,  0.9046343 ]),
 np.array([ 0.2909722 , -0.46851484,  1.03386778]),
 np.array([ 0.47418649, -0.46851484,  1.03386778])])

In [8]:
diff = A - B

ValueError: operands could not be broadcast together with shapes (2,3,1) (4,3) 